"""Unit tests for pin_override.py. No network: `published` is monkeypatched everywhere.

Run: uv run --no-project --with pytest pytest test_pin_override.py -v
"""
from __future__ import annotations

import json

import pin_override as p
import pytest


# ------------------------------------------------------------------ versions

def test_parse_rejects_prereleases_and_junk():
    assert p.parse("1.2.3") == (1, 2, 3)
    assert p.parse("7.5.21") == (7, 5, 21)
    assert p.parse("1.2.3-rc.1") is None
    assert p.parse("4.0.0+build") is None
    assert p.parse("latest") is None
    assert p.parse("") is None


def test_zero_major_keeps_the_minor_as_the_compatibility_line():
    # esbuild ships 0.21.5 and 0.28.1 in one tree with a fix in 0.25.0. Keyed on the major
    # alone these are one line, and "fixing" 0.21.5 with 0.25.0 is a breaking bump.
    assert p.line_of("0.21.5") == (0, 21)
    assert p.line_of("0.25.0") == (0, 25)
    assert p.line_of("0.21.5") != p.line_of("0.25.0")
    # Above 0.x the major is the line.
    assert p.line_of("7.28.0") == (7,)
    assert p.line_of("7.29.1") == (7,)
    assert p.line_of("6.28.0") == (6,)


@pytest.mark.parametrize("version,spec,expected", [
    # the shapes the yarn audit feed actually emits
    ("1.1.16", "<1.1.17", True),
    ("1.1.18", "<1.1.17", False),
    ("5.0.7", ">=4.0.0 <5.0.8", True),
    ("5.0.9", ">=4.0.0 <5.0.8", False),
    ("3.9.9", ">=4.0.0 <5.0.8", False),
    ("9.1.0", "<=9.1.0", True),
    ("9.1.1", "<=9.1.0", False),
    ("12.0.2", "12.0.2", True),
    ("12.0.3", "12.0.2", False),
    ("3.5.0", ">=3.0.0 <3.15.2 || >=4.0.0 <4.3.2", True),
    ("4.2.0", ">=3.0.0 <3.15.2 || >=4.0.0 <4.3.2", True),
    ("4.3.2", ">=3.0.0 <3.15.2 || >=4.0.0 <4.3.2", False),
    ("1.2.3-rc.1", "<2.0.0", False),
])
def test_in_range(version, spec, expected):
    assert p.in_range(version, spec) is expected


def test_in_range_pads_uneven_lengths():
    assert p.in_range("3.15", "<3.15.2") is True
    assert p.in_range("3.15.2", "<3.15.2") is False


# ------------------------------------------------------------------ the tree

LOCK = '''# This file is generated by running "yarn install"
__metadata:
  version: 8

"brace-expansion@npm:^1.1.7":
  version: 1.1.16
  resolution: "brace-expansion@npm:1.1.16"
  languageName: node
  linkType: hard

"brace-expansion@npm:^5.0.5":
  version: 5.0.7
  resolution: "brace-expansion@npm:5.0.7"
  languageName: node
  linkType: hard

"minimatch@npm:3.1.5":
  version: 3.1.5
  resolution: "minimatch@npm:3.1.5"
  dependencies:
    brace-expansion: "npm:^1.1.7"
  languageName: node
  linkType: hard

"minimatch@npm:10.2.5":
  version: 10.2.5
  resolution: "minimatch@npm:10.2.5"
  languageName: node
  linkType: hard

"cheerio@npm:1.2.0":
  version: 1.2.0
  resolution: "cheerio@npm:1.2.0"
  dependencies:
    undici: "npm:^7.19.0"
  languageName: node
  linkType: hard

"undici@npm:6.28.0":
  version: 6.28.0
  resolution: "undici@npm:6.28.0"
  languageName: node
  linkType: hard

"undici@npm:^7.19.0":
  version: 7.28.0
  resolution: "undici@npm:7.28.0"
  languageName: node
  linkType: hard

"qs@npm:6.15.3, qs@npm:^6.11.0, qs@npm:^6.14.0":
  version: 6.15.3
  resolution: "qs@npm:6.15.3"
  languageName: node
  linkType: hard
'''


@pytest.fixture()
def tree(tmp_path):
    lock = tmp_path / "yarn.lock"
    lock.write_text(LOCK)
    return p.lock_versions(lock)


def test_lock_versions_collects_every_line_of_a_package(tree):
    assert tree["brace-expansion"] == {"1.1.16", "5.0.7"}
    assert tree["undici"] == {"6.28.0", "7.28.0"}
    assert tree["minimatch"] == {"3.1.5", "10.2.5"}


def test_lock_versions_folds_a_multi_descriptor_entry(tree):
    # One entry, four descriptors, one resolved version — the qs shape.
    assert tree["qs"] == {"6.15.3"}


def test_lock_versions_tolerates_a_missing_lockfile(tmp_path):
    assert p.lock_versions(tmp_path / "nope.lock") == {}


@pytest.mark.parametrize("raw,expected", [
    ("minimatch@npm:3.1.5", "minimatch"),
    ("@strapi/core@npm:5.52.2", "@strapi/core"),
    ("cheerio@npm:1.2.0", "cheerio"),
    ("wemove-frontend@workspace:.", None),
    ("nonsense", None),
])
def test_dependent_name(raw, expected):
    assert p.dependent_name(raw) == expected


# ------------------------------------------------------------------ descriptor

def test_single_line_gets_an_unscoped_resolution(tree):
    # qs: ~20 @strapi/* parents deduped onto ONE entry. A scoped key would fork a second
    # entry and leave 6.15.3 for the other nineteen.
    key, why = p.descriptor_for("qs", "6.15.3", ["@strapi/admin@npm:5.52.2"], tree)
    assert key == "qs", why


def test_multi_line_with_one_single_version_parent_is_scoped_to_that_parent(tree):
    # undici 7.x comes only from cheerio (^7.19.0); 6.28.0 is Strapi's exact pin and is not
    # in the advisory. The key carries no parent VERSION so it survives a cheerio bump.
    key, why = p.descriptor_for("undici", "7.28.0", ["cheerio@npm:1.2.0"], tree)
    assert key == "cheerio/undici", why


def test_multi_line_is_refused_when_the_parent_itself_has_several_versions(tree):
    # minimatch 3.1.5 wants ^1.1.7 and 10.2.5 wants ^5.0.5. `minimatch/brace-expansion`
    # would drag both lines onto one version; the correct key embeds a parent version that
    # rots on the next minimatch bump. Human's call.
    key, why = p.descriptor_for("brace-expansion", "1.1.16",
                                ["minimatch@npm:3.1.5"], tree)
    assert key is None
    assert "2 versions" in why


def test_multi_line_is_refused_when_several_parents_pull_it(tree):
    key, why = p.descriptor_for("undici", "7.28.0",
                                ["cheerio@npm:1.2.0", "got@npm:14.0.0"], tree)
    assert key is None
    assert "several parents" in why


def test_multi_line_is_refused_when_the_only_dependent_is_the_workspace(tree):
    key, why = p.descriptor_for("undici", "7.28.0", ["myapp@workspace:."], tree)
    assert key is None
    assert "no named parent" in why


# ------------------------------------------------------------------ planning

def _pkg(tmp_path, **fields):
    (tmp_path / "package.json").write_text(json.dumps({"name": "t", **fields}))
    (tmp_path / "yarn.lock").write_text(LOCK)
    return tmp_path


def _adv(pkg, ghsa, vulnerable, installed, dependents, severity="high"):
    return {"pkg": pkg, "ghsa": ghsa, "severity": severity, "vulnerable": vulnerable,
            "installed": installed, "dependents": dependents, "issue": ""}


def test_a_direct_dependency_is_left_to_dependabot(tmp_path, monkeypatch):
    root = _pkg(tmp_path, dependencies={"qs": "^6.15.0"})
    monkeypatch.setattr(p, "published", lambda _: ["6.15.3", "6.16.0"])
    proposals, blocked = p.plan(
        [_adv("qs", "GHSA-1", "<6.16.0", ["6.15.3"], ["@strapi/admin@npm:5.52.2"])],
        root, p.lock_versions(root / "yarn.lock"))
    assert proposals == []
    assert "direct dependency" in blocked[0]["why"]


def test_a_cross_line_fix_is_named_not_attempted(tmp_path, monkeypatch):
    root = _pkg(tmp_path)
    # stream-json 1.9.1, fix in 3.5.0: nothing inside the 1.x line helps.
    monkeypatch.setattr(p, "published", lambda _: ["1.9.1", "3.5.0"])
    proposals, blocked = p.plan(
        [_adv("stream-json", "GHSA-2", "<=3.4.0", ["1.9.1"], ["@strapi/x@npm:5.0.0"])],
        root, p.lock_versions(root / "yarn.lock"))
    assert proposals == []
    assert "no fix inside the 1.x line" in blocked[0]["why"]


def test_several_advisories_on_one_line_collapse_to_one_resolution(tmp_path, monkeypatch):
    root = _pkg(tmp_path)
    monkeypatch.setattr(p, "published", lambda _: ["7.28.0", "7.29.0", "7.29.1"])
    advisories = [
        _adv("undici", "GHSA-A", ">=7.0.0 <7.29.0", ["7.28.0"], ["cheerio@npm:1.2.0"]),
        _adv("undici", "GHSA-B", ">=7.0.0 <7.29.0", ["7.28.0"], ["cheerio@npm:1.2.0"],
             severity="critical"),
    ]
    proposals, _ = p.plan(advisories, root, p.lock_versions(root / "yarn.lock"))
    assert len(proposals) == 1
    assert proposals[0]["key"] == "cheerio/undici"
    # Newest in the line, not either advisory's first patched version.
    assert proposals[0]["target"] == "7.29.1"
    assert proposals[0]["ghsas"] == {"GHSA-A", "GHSA-B"}
    assert proposals[0]["severity"] == "critical"


def test_a_target_still_inside_the_vulnerable_range_is_refused(tmp_path, monkeypatch):
    root = _pkg(tmp_path)
    # Newest in the 6.x line is 6.15.3, which is itself vulnerable — proposing it would be
    # a pin that fixes nothing.
    monkeypatch.setattr(p, "published", lambda _: ["6.15.2", "6.15.3", "7.0.0"])
    proposals, blocked = p.plan(
        [_adv("qs", "GHSA-3", "<6.16.0", ["6.15.3"], ["@strapi/admin@npm:5.52.2"])],
        root, p.lock_versions(root / "yarn.lock"))
    assert proposals == []
    assert blocked


def test_an_advisory_whose_installed_versions_are_all_safe_is_ignored(tmp_path,
                                                                     monkeypatch):
    root = _pkg(tmp_path)
    monkeypatch.setattr(p, "published", lambda _: ["6.28.0", "6.29.0"])
    proposals, blocked = p.plan(
        [_adv("undici", "GHSA-4", ">=7.0.0 <7.29.0", ["6.28.0"], ["x@npm:1.0.0"])],
        root, p.lock_versions(root / "yarn.lock"))
    assert proposals == []
    assert blocked == []


# ------------------------------------------------------------------ writing

def test_resolutions_round_trip(tmp_path):
    root = _pkg(tmp_path, resolutions={"lodash": "^4.18.0"})
    before = p.apply_resolutions(root, {"tar": "^7.5.22"})
    assert before == {"lodash": "^4.18.0"}
    got = json.loads((root / "package.json").read_text())["resolutions"]
    assert got == {"lodash": "^4.18.0", "tar": "^7.5.22"}
    p.restore_resolutions(root, before)
    got = json.loads((root / "package.json").read_text())["resolutions"]
    assert got == {"lodash": "^4.18.0"}


def test_restore_removes_the_key_entirely_when_there_was_none(tmp_path):
    root = _pkg(tmp_path)
    p.apply_resolutions(root, {"tar": "^7.5.22"})
    p.restore_resolutions(root, {})
    assert "resolutions" not in json.loads((root / "package.json").read_text())


def test_apply_overwrites_an_existing_entry_rather_than_duplicating(tmp_path):
    root = _pkg(tmp_path, resolutions={"tar": "^7.5.19"})
    p.apply_resolutions(root, {"tar": "^7.5.22"})
    got = json.loads((root / "package.json").read_text())["resolutions"]
    assert got == {"tar": "^7.5.22"}


# ------------------------------------------------------------------ audit

def test_audit_drops_deprecation_notices(monkeypatch, tmp_path):
    lines = [
        # A deprecation notice: string ID, no GHSA URL. Must never become a pin.
        json.dumps({"value": "@koa/router", "children": {
            "ID": "@koa/router (deprecation)", "Severity": "moderate",
            "Issue": "Please upgrade", "Vulnerable Versions": "12.0.2",
            "Tree Versions": ["12.0.2"], "Dependents": ["@strapi/core@npm:5.52.2"]}}),
        json.dumps({"value": "tar", "children": {
            "ID": 1130588, "Severity": "high", "Issue": "node-tar: recursion",
            "URL": "https://github.com/advisories/GHSA-r292-9mhp-454m",
            "Vulnerable Versions": "<=7.5.20", "Tree Versions": ["7.5.19"],
            "Dependents": ["node-gyp@npm:12.1.0"]}}),
        "",
        "not json at all",
    ]

    class Proc:
        stdout = "\n".join(lines)
        stderr = ""
        returncode = 1  # yarn exits non-zero whenever it finds anything

    monkeypatch.setattr(p, "run", lambda *a, **k: Proc())
    got = p.audit(tmp_path)
    assert len(got) == 1
    assert got[0]["pkg"] == "tar"
    assert got[0]["ghsa"] == "GHSA-R292-9MHP-454M"
    assert got[0]["installed"] == ["7.5.19"]


# ------------------------------------------------------------------ reporting

def test_blocked_report_states_each_reason_once(tmp_path):
    blocked = [
        {"pkg": "brace-expansion", "installed_one": "1.1.16", "severity": "high",
         "why": "minimatch is itself in the tree at 2 versions"},
        {"pkg": "brace-expansion", "installed_one": "1.1.16", "severity": "high",
         "why": "minimatch is itself in the tree at 2 versions"},
        {"pkg": "vite", "installed_one": "5.4.21", "severity": "high",
         "why": "no fix inside the 5.x line"},
    ]
    out = p.render_blocked(blocked)
    assert out.count("brace-expansion") == 1
    assert out.count("vite") == 1


def test_summary_reads_as_a_sentence():
    applied = [{"key": "tar", "target": "7.5.22", "severity": "high", "ghsas": {"G1"}},
               {"key": "cheerio/undici", "target": "7.29.1", "severity": "high",
                "ghsas": {"G2", "G3"}}]
    got = p.summarise(applied, [], [{"pkg": "vite"}])
    assert "tar -> ^7.5.22 (high, 1 advisory)" in got
    assert "cheerio/undici -> ^7.29.1 (high, 2 advisories)" in got
    assert "1 need a human" in got
    assert p.summarise([], [], []) == "nothing to change"


# ------------------------------------------------------------------ the bump pass

LOCK_AFTER = LOCK.replace("version: 1.1.16", "version: 1.1.18").replace(
    "version: 5.0.7", "version: 5.0.9").replace("version: 6.15.3", "version: 6.16.0")


class _Yarn:
    """Fake `run`: a `yarn up` rewrites the lockfile to LOCK_AFTER (or to `lock_after`
    if given) and records every command; anything else exits 0 with no output."""

    def __init__(self, root, rc=0, rewrite_manifest=False, lock_after=LOCK_AFTER):
        self.root, self.rc, self.rewrite_manifest = root, rc, rewrite_manifest
        self.lock_after, self.calls = lock_after, []

    def __call__(self, cmd, cwd, check=False):
        self.calls.append(cmd)

        class Proc:
            returncode = self.rc
            stdout = ""
            stderr = "boom" if self.rc else ""
        if cmd[:2] == ["yarn", "up"] and self.rc == 0:
            (self.root / "yarn.lock").write_text(self.lock_after)
            if self.rewrite_manifest:
                (self.root / "package.json").write_text('{"name": "changed"}')
        return Proc()


def _audits(monkeypatch, *results):
    """`audit` returns each result in turn, then the last one forever."""
    queue = list(results)

    def fake(root):
        return queue.pop(0) if len(queue) > 1 else queue[0]
    monkeypatch.setattr(p, "audit", fake)


def test_bump_keeps_what_cleared_and_touches_only_the_lockfile(tmp_path, monkeypatch):
    root = _pkg(tmp_path, dependencies={"qs": "^6.11.0"})
    manifest = (root / "package.json").read_text()
    yarn = _Yarn(root)
    monkeypatch.setattr(p, "run", yarn)
    before = [_adv("brace-expansion", "GHSA-A", "<1.1.17", ["1.1.16"], ["minimatch@npm:3.1.5"]),
              _adv("brace-expansion", "GHSA-B", ">=4.0.0 <5.0.8", ["5.0.7"], ["x@npm:1"]),
              _adv("qs", "GHSA-C", "<6.16.0", ["6.15.3"], ["y@npm:1"], severity="low")]
    _audits(monkeypatch, [])                      # everything cleared
    bumped, left, note = p.bump_in_range(root, before)
    assert note == "" and left == []
    assert [b["pkg"] for b in bumped] == ["brace-expansion", "qs"]
    be = bumped[0]
    assert be["from"] == ["1.1.16", "5.0.7"] and be["to"] == ["1.1.18", "5.0.9"], be
    assert be["ghsas"] == {"GHSA-A", "GHSA-B"} and be["severity"] == "high"
    # A DIRECT dependency is bumped too: -R keeps the manifest range and moves the lock.
    assert bumped[1]["pkg"] == "qs"
    assert (root / "package.json").read_text() == manifest
    assert len(yarn.calls) == 1
    assert yarn.calls[0][:3] == ["yarn", "up", "-R"] and "--mode=update-lockfile" in yarn.calls[0]


def test_a_package_that_moved_without_clearing_is_put_back(tmp_path, monkeypatch):
    root = _pkg(tmp_path)
    yarn = _Yarn(root)
    monkeypatch.setattr(p, "run", yarn)
    before = [_adv("brace-expansion", "GHSA-A", "<1.1.17", ["1.1.16"], ["m@npm:3"]),
              _adv("qs", "GHSA-C", "<6.17.0", ["6.15.3"], ["y@npm:1"])]
    still_qs = [_adv("qs", "GHSA-C", "<6.17.0", ["6.16.0"], ["y@npm:1"])]
    _audits(monkeypatch, still_qs, still_qs)      # qs moved to 6.16.0, still vulnerable
    bumped, left, note = p.bump_in_range(root, before)
    assert [b["pkg"] for b in bumped] == ["brace-expansion"]
    assert left == still_qs
    # Two runs: the discovery run with both names, then the keep run with only the helpful.
    assert len(yarn.calls) == 2
    assert "qs" in yarn.calls[0] and "qs" not in yarn.calls[1]
    assert "brace-expansion" in yarn.calls[1]


def test_nothing_cleared_means_nothing_kept(tmp_path, monkeypatch):
    root = _pkg(tmp_path)
    monkeypatch.setattr(p, "run", _Yarn(root))
    before = [_adv("qs", "GHSA-C", "<6.17.0", ["6.15.3"], ["y@npm:1"])]
    _audits(monkeypatch, before)
    bumped, left, note = p.bump_in_range(root, before)
    assert bumped == [] and left == before and note == ""
    assert (root / "yarn.lock").read_text() == LOCK            # restored byte for byte


def test_a_rewritten_manifest_abandons_the_pass(tmp_path, monkeypatch):
    root = _pkg(tmp_path, dependencies={"qs": "^6.11.0"})
    manifest = (root / "package.json").read_text()
    monkeypatch.setattr(p, "run", _Yarn(root, rewrite_manifest=True))
    before = [_adv("qs", "GHSA-C", "<6.16.0", ["6.15.3"], ["y@npm:1"])]
    _audits(monkeypatch, [])
    bumped, left, note = p.bump_in_range(root, before)
    assert bumped == [] and left == before
    assert "package.json" in note
    assert (root / "package.json").read_text() == manifest
    assert (root / "yarn.lock").read_text() == LOCK


def test_a_failed_yarn_up_restores_and_says_why(tmp_path, monkeypatch):
    root = _pkg(tmp_path)
    monkeypatch.setattr(p, "run", _Yarn(root, rc=1))
    before = [_adv("qs", "GHSA-C", "<6.16.0", ["6.15.3"], ["y@npm:1"])]
    _audits(monkeypatch, before)
    bumped, left, note = p.bump_in_range(root, before)
    assert bumped == [] and left == before
    assert "failed" in note and "boom" in note
    assert (root / "yarn.lock").read_text() == LOCK


def test_no_advisories_means_no_yarn_run_at_all(tmp_path, monkeypatch):
    root = _pkg(tmp_path)
    yarn = _Yarn(root)
    monkeypatch.setattr(p, "run", yarn)
    assert p.bump_in_range(root, []) == ([], [], "")
    assert yarn.calls == []


def test_bumped_report_names_versions_and_advisories():
    out = p.render_bumped([{"pkg": "axios", "from": ["1.9.0"], "to": ["1.20.0"],
                            "severity": "high", "ghsas": {"GHSA-B", "GHSA-A"}}])
    assert out == "- `axios` 1.9.0 → 1.20.0 (high, GHSA-A, GHSA-B)"


def test_summary_counts_the_bump_pass_first():
    bumped = [{"pkg": "axios", "ghsas": {"A", "B"}}, {"pkg": "qs", "ghsas": {"C"}}]
    got = p.summarise([], [], [], bumped)
    assert got.startswith("2 packages re-resolved in range (3 advisories)"), got
    applied = [{"key": "tar", "target": "7.5.22", "severity": "high", "ghsas": {"G1"}}]
    got = p.summarise(applied, [], [{"pkg": "vite"}], bumped)
    assert "re-resolved" in got and "tar -> ^7.5.22" in got and "1 need a human" in got


# ------------------------------------------------------------------ npm ranges (parent pass)

@pytest.mark.parametrize("version,rng,expected", [
    # the shapes a package.json actually declares
    ("10.7.2", "^10.1.1", True),
    ("10.0.9", "^10.1.1", False),
    ("11.0.0", "^10.1.1", False),
    ("0.34.5", "^0.34.3", True),
    ("0.35.0", "^0.34.3", False),          # 0.x: the minor is the line
    ("0.0.3", "^0.0.3", True),
    ("0.0.4", "^0.0.3", False),
    ("1.2.9", "~1.2.3", True),
    ("1.3.0", "~1.2.3", False),
    ("1.5.0", "1.x", True),
    ("2.0.0", "1.x", False),
    ("1.2.3", "1.2.3", True),
    ("1.2.4", "1.2.3", False),
    ("5.0.0", ">=4.0.0 <6", True),
    ("6.0.0", ">=4.0.0 <6", False),
    ("1.3.0", ">1.2", True),               # node-semver: >1.2 means >=1.3.0
    ("1.2.5", ">1.2", False),
    ("2.3.9", "1.2 - 2.3", True),
    ("2.4.0", "1.2 - 2.3", False),
    ("9.9.9", "*", True),
    ("3.0.0", "^1 || ^3", True),
    ("2.0.0", "^1 || ^3", False),
    ("1.2.3-rc.1", "^1.2.0", False),       # prereleases never satisfy
    ("1.0.0", "workspace:*", False),       # protocols and tags never satisfy
    ("1.0.0", "npm:foo@^1", False),
    ("1.0.0", "latest", False),
])
def test_satisfies(version, rng, expected):
    assert p.satisfies(version, rng) is expected


@pytest.mark.parametrize("raw,expected", [
    ("socks@npm:2.8.4", ("socks", "2.8.4")),
    ("@strapi/core@npm:5.52.2", ("@strapi/core", "5.52.2")),
    ("wemove-frontend@workspace:.", None),
    ("resolve@patch:resolve@npm%3A1.22.1#optional!builtin<compat/resolve>", None),
    ("x@npm:1.0.0-rc.1", None),            # not on a line, never a candidate
    ("nonsense", None),
])
def test_dependent_pair(raw, expected):
    assert p.dependent_pair(raw) == expected


# ------------------------------------------------------------------ the parent pass

REGISTRY = {
    "socks": {
        "2.8.4": {"dependencies": {"ip-address": "^9.0.5", "smart-buffer": "^4.2.0"}},
        "2.8.5": {"dependencies": {"ip-address": "^9.0.5", "smart-buffer": "^4.2.0"}},
        "2.8.10": {"dependencies": {"ip-address": "^10.1.1", "smart-buffer": "^4.2.0"}},
        "3.0.0": {"dependencies": {"ip-address": "^10.1.1"}},
    },
    "ip-address": {"9.0.5": {}, "10.3.1": {}, "10.7.2": {}},
    "dropper": {"1.0.0": {"dependencies": {"ip-address": "^9.0.5"}},
                "1.1.0": {"dependencies": {}}},
    "stuck": {"1.0.0": {"dependencies": {"ip-address": "^9.0.5"}},
              "1.0.1": {"dependencies": {"ip-address": "^9.0.5"}},
              "2.0.0": {"dependencies": {"ip-address": "^10.1.1"}}},
}


@pytest.fixture()
def registry(monkeypatch):
    monkeypatch.setattr(p, "registry_versions", lambda pkg: REGISTRY.get(pkg, {}))


def test_parent_target_picks_the_newest_in_line_release_that_admits_the_fix(registry):
    # socks 2.8.4 wants ^9.0.5; 2.8.10 wants ^10.1.1, which Yarn resolves to 10.7.2 —
    # outside the advisory. 3.0.0 would too, but that is socks' next line: never.
    assert p.parent_target("socks", "2.8.4", "ip-address", "<=10.3.0") == "2.8.10"


def test_parent_target_refuses_when_no_in_line_release_helps(registry):
    # stuck 1.0.1 still wants ^9.0.5; the only release that admits the fix is 2.0.0.
    assert p.parent_target("stuck", "1.0.0", "ip-address", "<=10.3.0") is None


def test_parent_target_accepts_a_release_that_dropped_the_child(registry):
    assert p.parent_target("dropper", "1.0.0", "ip-address", "<=10.3.0") == "1.1.0"


def test_parent_target_needs_a_placeable_installed_version(registry):
    assert p.parent_target("socks", "2.8.4-beta.1", "ip-address", "<=10.3.0") is None
    assert p.parent_target("socks", "2.8.10", "ip-address", "<=10.3.0") is None  # already newest


LOCK_PARENT = '''# This file is generated by running "yarn install"
__metadata:
  version: 8

"ip-address@npm:^9.0.5":
  version: 9.0.5
  resolution: "ip-address@npm:9.0.5"
  languageName: node
  linkType: hard

"socks@npm:^2.8.3":
  version: 2.8.4
  resolution: "socks@npm:2.8.4"
  dependencies:
    ip-address: "npm:^9.0.5"
  languageName: node
  linkType: hard
'''
LOCK_PARENT_AFTER = LOCK_PARENT.replace('"ip-address@npm:^9.0.5"', '"ip-address@npm:^10.1.1"') \
    .replace("version: 9.0.5", "version: 10.7.2").replace("ip-address@npm:9.0.5", "ip-address@npm:10.7.2") \
    .replace("version: 2.8.4", "version: 2.8.10").replace("socks@npm:2.8.4", "socks@npm:2.8.10") \
    .replace('ip-address: "npm:^9.0.5"', 'ip-address: "npm:^10.1.1"')


def _pkg_parent(tmp_path):
    (tmp_path / "package.json").write_text(json.dumps({"name": "t"}))
    (tmp_path / "yarn.lock").write_text(LOCK_PARENT)
    return tmp_path


def test_bump_parents_moves_the_parent_and_reports_the_child(tmp_path, monkeypatch, registry):
    root = _pkg_parent(tmp_path)
    yarn = _Yarn(root, lock_after=LOCK_PARENT_AFTER)
    monkeypatch.setattr(p, "run", yarn)
    adv = [_adv("ip-address", "GHSA-IP", "<=10.3.0", ["9.0.5"], ["socks@npm:2.8.4"])]
    _audits(monkeypatch, [])
    bumped, left, note = p.bump_parents(root, adv)
    assert note == "" and left == []
    assert len(bumped) == 1
    b = bumped[0]
    assert b["pkg"] == "socks" and b["from"] == ["2.8.4"] and b["to"] == ["2.8.10"]
    assert b["child"] == "ip-address" and b["child_from"] == ["9.0.5"] and b["child_to"] == ["10.7.2"]
    assert b["ghsas"] == {"GHSA-IP"} and b["severity"] == "high"
    # It is the PARENT that is re-resolved, not the child (the first pass already tried that).
    assert len(yarn.calls) == 1 and "socks" in yarn.calls[0] and "ip-address" not in yarn.calls[0]
    assert "--mode=update-lockfile" in yarn.calls[0]


def test_bump_parents_does_nothing_when_no_parent_release_helps(tmp_path, monkeypatch, registry):
    root = _pkg_parent(tmp_path)
    yarn = _Yarn(root)
    monkeypatch.setattr(p, "run", yarn)
    adv = [_adv("ip-address", "GHSA-IP", "<=10.3.0", ["9.0.5"], ["stuck@npm:1.0.0"])]
    bumped, left, note = p.bump_parents(root, adv)
    assert bumped == [] and left == adv and note == ""
    assert yarn.calls == []
    assert (root / "yarn.lock").read_text() == LOCK_PARENT


def test_bump_parents_puts_back_a_parent_that_moved_without_clearing(tmp_path, monkeypatch, registry):
    root = _pkg_parent(tmp_path)
    yarn = _Yarn(root, lock_after=LOCK_PARENT_AFTER)
    monkeypatch.setattr(p, "run", yarn)
    adv = [_adv("ip-address", "GHSA-IP", "<=10.3.0", ["9.0.5"], ["socks@npm:2.8.4"])]
    _audits(monkeypatch, adv)                     # still open after the move
    bumped, left, note = p.bump_parents(root, adv)
    assert bumped == [] and left == adv and note == ""
    assert (root / "yarn.lock").read_text() == LOCK_PARENT


def test_bump_parents_ignores_advisories_whose_installed_copies_are_safe(tmp_path, monkeypatch, registry):
    root = _pkg_parent(tmp_path)
    yarn = _Yarn(root)
    monkeypatch.setattr(p, "run", yarn)
    adv = [_adv("ip-address", "GHSA-IP", "<=10.3.0", ["10.7.2"], ["socks@npm:2.8.10"])]
    assert p.bump_parents(root, adv) == ([], adv, "")
    assert yarn.calls == []


def test_bumped_report_names_the_child_a_parent_moved():
    out = p.render_bumped([{"pkg": "socks", "from": ["2.8.4"], "to": ["2.8.10"],
                            "child": "ip-address", "child_from": ["9.0.5"], "child_to": ["10.7.2"],
                            "severity": "high", "ghsas": {"GHSA-IP"}}])
    assert out == "- `socks` 2.8.4 → 2.8.10 — parent of `ip-address` 9.0.5 → 10.7.2 (high, GHSA-IP)"


# ------------------------------------------------------------------ the python pass (uv)

UV_LOCK = '''version = 1
revision = 3
requires-python = ">=3.13"

[[package]]
name = "click"
version = "8.3.0"
source = { registry = "https://pypi.org/simple" }

[[package]]
name = "cryptography"
version = "49.0.0"
source = { registry = "https://pypi.org/simple" }

[[package]]
name = "Flask_Cors"
version = "6.0.5"
source = { registry = "https://pypi.org/simple" }
'''
UV_LOCK_AFTER = UV_LOCK.replace('version = "8.3.0"', 'version = "8.3.3"')


@pytest.mark.parametrize("installed,bound", [
    ("1.9.1", "<2"), ("3.20", "<4"), ("0.21.5", "<0.22"), ("49.0.0", "<50"), ("1.0.0rc1", ""),
])
def test_uv_line_bound(installed, bound):
    assert p.uv_line_bound(installed) == bound


def test_uv_lock_versions_normalises_names(tmp_path):
    lock = tmp_path / "uv.lock"
    lock.write_text(UV_LOCK)
    got = p.uv_lock_versions(lock)
    assert got["click"] == {"8.3.0"} and got["flask-cors"] == {"6.0.5"}
    assert p.uv_lock_versions(tmp_path / "nope.lock") == {}


PIP_AUDIT_JSON = json.dumps({"dependencies": [
    {"name": "click", "version": "8.3.0", "vulns": [
        {"id": "PYSEC-2026-2132", "aliases": ["GHSA-47fr-3ffg-hgmw", "CVE-2026-7246"],
         "fix_versions": ["8.3.3"]}]},
    {"name": "cryptography", "version": "49.0.0", "vulns": [
        {"id": "PYSEC-2026-3552", "aliases": ["CVE-2026-69247"], "fix_versions": ["50.0.0"]}]},
    {"name": "flask", "version": "3.1.3", "vulns": []},
], "fixes": []})


class _Uv:
    """Fake `run` for the uv pass: `uv export` succeeds silently, `pip-audit` answers with
    `audit_json`, `uv lock` rewrites uv.lock to `lock_after`; records every command."""

    def __init__(self, root, audit_json=PIP_AUDIT_JSON, lock_after=UV_LOCK_AFTER, rc=0,
                 rewrite_manifest=False):
        self.root, self.audit_json, self.lock_after = root, audit_json, lock_after
        self.rc, self.rewrite_manifest, self.calls = rc, rewrite_manifest, []

    def __call__(self, cmd, cwd, check=False):
        self.calls.append(cmd)

        class Proc:
            returncode = 0
            stdout = ""
            stderr = ""
        if cmd[:2] == ["uv", "lock"]:
            Proc.returncode = self.rc
            Proc.stderr = "boom" if self.rc else ""
            if not self.rc:
                (self.root / "uv.lock").write_text(self.lock_after)
                if self.rewrite_manifest:
                    (self.root / "pyproject.toml").write_text("[project]\nname='changed'\n")
        elif "pip-audit" in cmd:
            Proc.returncode = 1                    # pip-audit exits 1 when it finds anything
            Proc.stdout = self.audit_json
        return Proc()


def _py(tmp_path):
    (tmp_path / "pyproject.toml").write_text('[project]\nname = "t"\nversion = "0"\n')
    (tmp_path / "uv.lock").write_text(UV_LOCK)
    return tmp_path


def test_uv_audit_reads_pip_audit_and_prefers_the_ghsa_alias(tmp_path, monkeypatch):
    root = _py(tmp_path)
    uv = _Uv(root)
    monkeypatch.setattr(p, "run", uv)
    got = p.uv_audit(root)
    assert [(g["pkg"], g["installed"], g["ghsa"], g["fix"]) for g in got] == [
        ("click", ["8.3.0"], "GHSA-47FR-3FFG-HGMW", ["8.3.3"]),
        ("cryptography", ["49.0.0"], "PYSEC-2026-3552", ["50.0.0"]),
    ]
    assert uv.calls[0][:2] == ["uv", "export"] and "--frozen" in uv.calls[0]
    assert "--no-deps" in uv.calls[1] and "--disable-pip" in uv.calls[1]
    assert not (root / ".pin-override-export.txt").exists()      # cleaned up


def test_uv_audit_refuses_to_read_non_json_as_clean(tmp_path, monkeypatch):
    root = _py(tmp_path)
    monkeypatch.setattr(p, "run", _Uv(root, audit_json="ERROR: something"))
    with pytest.raises(SystemExit):
        p.uv_audit(root)


def _uv_audits(monkeypatch, *results):
    queue = list(results)

    def fake(root):
        return queue.pop(0) if len(queue) > 1 else queue[0]
    monkeypatch.setattr(p, "uv_audit", fake)


def _f(pkg, ver, ghsa, fix):
    return {"pkg": pkg, "installed": [ver], "ghsa": ghsa, "fix": fix, "severity": "unknown",
            "vulnerable": "", "dependents": []}


def test_uv_pass_keeps_what_cleared_inside_its_line_and_puts_the_rest_back(tmp_path, monkeypatch):
    root = _py(tmp_path)
    manifest = (root / "pyproject.toml").read_text()
    uv = _Uv(root)
    monkeypatch.setattr(p, "run", uv)
    before = [_f("click", "8.3.0", "GHSA-CLICK", ["8.3.3"]),
              _f("cryptography", "49.0.0", "GHSA-CRYPTO", ["50.0.0"])]
    still = [_f("cryptography", "49.0.0", "GHSA-CRYPTO", ["50.0.0"])]
    _uv_audits(monkeypatch, before, still, still)   # cryptography cannot move inside 49.x
    bumped, left, note = p.bump_uv_in_range(root)
    assert note == "" and left == still
    assert [(b["pkg"], b["from"], b["to"], b["ghsas"]) for b in bumped] == [
        ("click", ["8.3.0"], ["8.3.3"], {"GHSA-CLICK"})]
    locks = [c for c in uv.calls if c[:2] == ["uv", "lock"]]
    # Discovery run with both, bounded to their own lines; keep run with click alone.
    assert locks[0][2:] == ["-P", "click<9", "-P", "cryptography<50"]
    assert locks[1][2:] == ["-P", "click<9"]
    assert (root / "pyproject.toml").read_text() == manifest
    assert p.uv_blocked(left)[0]["why"] == "no fix inside the 49.x line"


def test_uv_pass_restores_when_nothing_cleared(tmp_path, monkeypatch):
    root = _py(tmp_path)
    monkeypatch.setattr(p, "run", _Uv(root))
    before = [_f("cryptography", "49.0.0", "GHSA-CRYPTO", ["50.0.0"])]
    _uv_audits(monkeypatch, before)
    bumped, left, note = p.bump_uv_in_range(root)
    assert bumped == [] and left == before and note == ""
    assert (root / "uv.lock").read_text() == UV_LOCK


def test_uv_pass_abandons_when_pyproject_changes(tmp_path, monkeypatch):
    root = _py(tmp_path)
    manifest = (root / "pyproject.toml").read_text()
    monkeypatch.setattr(p, "run", _Uv(root, rewrite_manifest=True))
    before = [_f("click", "8.3.0", "GHSA-CLICK", ["8.3.3"])]
    _uv_audits(monkeypatch, before, [])
    bumped, left, note = p.bump_uv_in_range(root)
    assert bumped == [] and left == before and "pyproject.toml" in note
    assert (root / "pyproject.toml").read_text() == manifest
    assert (root / "uv.lock").read_text() == UV_LOCK


def test_uv_pass_reports_a_failed_lock(tmp_path, monkeypatch):
    root = _py(tmp_path)
    monkeypatch.setattr(p, "run", _Uv(root, rc=1))
    before = [_f("click", "8.3.0", "GHSA-CLICK", ["8.3.3"])]
    _uv_audits(monkeypatch, before)
    bumped, left, note = p.bump_uv_in_range(root)
    assert bumped == [] and left == before and "failed" in note and "boom" in note


def test_uv_blocked_names_a_missing_fix():
    assert p.uv_blocked([_f("ecdsa", "0.19.2", "GHSA-E", [])])[0]["why"] == "no fixed version published"


def test_a_clean_uv_root_runs_no_lock(tmp_path, monkeypatch):
    root = _py(tmp_path)
    uv = _Uv(root)
    monkeypatch.setattr(p, "run", uv)
    _uv_audits(monkeypatch, [])
    assert p.bump_uv_in_range(root) == ([], [], "")
    assert not [c for c in uv.calls if c[:2] == ["uv", "lock"]]


# ------------------------------------------------------------------ dispatch

def test_main_handles_a_python_only_root(tmp_path, monkeypatch):
    import sys
    root = _py(tmp_path)
    out = tmp_path / "gh_output"
    monkeypatch.setenv("GITHUB_OUTPUT", str(out))
    monkeypatch.setattr(sys, "argv", ["pin_override.py", "--root", str(root)])
    monkeypatch.setattr(p, "bump_uv_in_range", lambda r: (
        [{"pkg": "click", "from": ["8.3.0"], "to": ["8.3.3"], "ghsas": {"GHSA-CLICK"},
          "severity": "unknown"}],
        [_f("cryptography", "49.0.0", "GHSA-CRYPTO", ["50.0.0"])], ""))
    assert p.main() == 0
    got = out.read_text()
    assert "changed=true" in got
    assert "`click` 8.3.0 → 8.3.3 (unknown, GHSA-CLICK)" in got
    assert "no fix inside the 49.x line" in got
    assert "1 package re-resolved in range (1 advisory)" in got


def test_main_refuses_a_root_with_neither_manifest(tmp_path, monkeypatch):
    import sys
    monkeypatch.setattr(sys, "argv", ["pin_override.py", "--root", str(tmp_path)])
    assert p.main() == 2
