"""Unit tests for pin_override.py. No network: `published` is monkeypatched everywhere.

Run: uv run --no-project --with pytest pytest test_pin_override.py -v
"""
from __future__ import annotations

import json

import pin_override as p
import pytest


# ------------------------------------------------------------------ versions

def test_parse_rejects_prereleases_and_junk():
    assert p.parse("1.2.3") == (1, 2, 3)
    assert p.parse("7.5.21") == (7, 5, 21)
    assert p.parse("1.2.3-rc.1") is None
    assert p.parse("4.0.0+build") is None
    assert p.parse("latest") is None
    assert p.parse("") is None


def test_zero_major_keeps_the_minor_as_the_compatibility_line():
    # esbuild ships 0.21.5 and 0.28.1 in one tree with a fix in 0.25.0. Keyed on the major
    # alone these are one line, and "fixing" 0.21.5 with 0.25.0 is a breaking bump.
    assert p.line_of("0.21.5") == (0, 21)
    assert p.line_of("0.25.0") == (0, 25)
    assert p.line_of("0.21.5") != p.line_of("0.25.0")
    # Above 0.x the major is the line.
    assert p.line_of("7.28.0") == (7,)
    assert p.line_of("7.29.1") == (7,)
    assert p.line_of("6.28.0") == (6,)


@pytest.mark.parametrize("version,spec,expected", [
    # the shapes the yarn audit feed actually emits
    ("1.1.16", "<1.1.17", True),
    ("1.1.18", "<1.1.17", False),
    ("5.0.7", ">=4.0.0 <5.0.8", True),
    ("5.0.9", ">=4.0.0 <5.0.8", False),
    ("3.9.9", ">=4.0.0 <5.0.8", False),
    ("9.1.0", "<=9.1.0", True),
    ("9.1.1", "<=9.1.0", False),
    ("12.0.2", "12.0.2", True),
    ("12.0.3", "12.0.2", False),
    ("3.5.0", ">=3.0.0 <3.15.2 || >=4.0.0 <4.3.2", True),
    ("4.2.0", ">=3.0.0 <3.15.2 || >=4.0.0 <4.3.2", True),
    ("4.3.2", ">=3.0.0 <3.15.2 || >=4.0.0 <4.3.2", False),
    ("1.2.3-rc.1", "<2.0.0", False),
])
def test_in_range(version, spec, expected):
    assert p.in_range(version, spec) is expected


def test_in_range_pads_uneven_lengths():
    assert p.in_range("3.15", "<3.15.2") is True
    assert p.in_range("3.15.2", "<3.15.2") is False


# ------------------------------------------------------------------ the tree

LOCK = '''# This file is generated by running "yarn install"
__metadata:
  version: 8

"brace-expansion@npm:^1.1.7":
  version: 1.1.16
  resolution: "brace-expansion@npm:1.1.16"
  languageName: node
  linkType: hard

"brace-expansion@npm:^5.0.5":
  version: 5.0.7
  resolution: "brace-expansion@npm:5.0.7"
  languageName: node
  linkType: hard

"minimatch@npm:3.1.5":
  version: 3.1.5
  resolution: "minimatch@npm:3.1.5"
  dependencies:
    brace-expansion: "npm:^1.1.7"
  languageName: node
  linkType: hard

"minimatch@npm:10.2.5":
  version: 10.2.5
  resolution: "minimatch@npm:10.2.5"
  languageName: node
  linkType: hard

"cheerio@npm:1.2.0":
  version: 1.2.0
  resolution: "cheerio@npm:1.2.0"
  dependencies:
    undici: "npm:^7.19.0"
  languageName: node
  linkType: hard

"undici@npm:6.28.0":
  version: 6.28.0
  resolution: "undici@npm:6.28.0"
  languageName: node
  linkType: hard

"undici@npm:^7.19.0":
  version: 7.28.0
  resolution: "undici@npm:7.28.0"
  languageName: node
  linkType: hard

"qs@npm:6.15.3, qs@npm:^6.11.0, qs@npm:^6.14.0":
  version: 6.15.3
  resolution: "qs@npm:6.15.3"
  languageName: node
  linkType: hard
'''


@pytest.fixture()
def tree(tmp_path):
    lock = tmp_path / "yarn.lock"
    lock.write_text(LOCK)
    return p.lock_versions(lock)


def test_lock_versions_collects_every_line_of_a_package(tree):
    assert tree["brace-expansion"] == {"1.1.16", "5.0.7"}
    assert tree["undici"] == {"6.28.0", "7.28.0"}
    assert tree["minimatch"] == {"3.1.5", "10.2.5"}


def test_lock_versions_folds_a_multi_descriptor_entry(tree):
    # One entry, four descriptors, one resolved version — the qs shape.
    assert tree["qs"] == {"6.15.3"}


def test_lock_versions_tolerates_a_missing_lockfile(tmp_path):
    assert p.lock_versions(tmp_path / "nope.lock") == {}


@pytest.mark.parametrize("raw,expected", [
    ("minimatch@npm:3.1.5", "minimatch"),
    ("@strapi/core@npm:5.52.2", "@strapi/core"),
    ("cheerio@npm:1.2.0", "cheerio"),
    ("wemove-frontend@workspace:.", None),
    ("nonsense", None),
])
def test_dependent_name(raw, expected):
    assert p.dependent_name(raw) == expected


# ------------------------------------------------------------------ descriptor

def test_single_line_gets_an_unscoped_resolution(tree):
    # qs: ~20 @strapi/* parents deduped onto ONE entry. A scoped key would fork a second
    # entry and leave 6.15.3 for the other nineteen.
    key, why = p.descriptor_for("qs", "6.15.3", ["@strapi/admin@npm:5.52.2"], tree)
    assert key == "qs", why


def test_multi_line_with_one_single_version_parent_is_scoped_to_that_parent(tree):
    # undici 7.x comes only from cheerio (^7.19.0); 6.28.0 is Strapi's exact pin and is not
    # in the advisory. The key carries no parent VERSION so it survives a cheerio bump.
    key, why = p.descriptor_for("undici", "7.28.0", ["cheerio@npm:1.2.0"], tree)
    assert key == "cheerio/undici", why


def test_multi_line_is_refused_when_the_parent_itself_has_several_versions(tree):
    # minimatch 3.1.5 wants ^1.1.7 and 10.2.5 wants ^5.0.5. `minimatch/brace-expansion`
    # would drag both lines onto one version; the correct key embeds a parent version that
    # rots on the next minimatch bump. Human's call.
    key, why = p.descriptor_for("brace-expansion", "1.1.16",
                                ["minimatch@npm:3.1.5"], tree)
    assert key is None
    assert "2 versions" in why


def test_multi_line_is_refused_when_several_parents_pull_it(tree):
    key, why = p.descriptor_for("undici", "7.28.0",
                                ["cheerio@npm:1.2.0", "got@npm:14.0.0"], tree)
    assert key is None
    assert "several parents" in why


def test_multi_line_is_refused_when_the_only_dependent_is_the_workspace(tree):
    key, why = p.descriptor_for("undici", "7.28.0", ["myapp@workspace:."], tree)
    assert key is None
    assert "no named parent" in why


# ------------------------------------------------------------------ planning

def _pkg(tmp_path, **fields):
    (tmp_path / "package.json").write_text(json.dumps({"name": "t", **fields}))
    (tmp_path / "yarn.lock").write_text(LOCK)
    return tmp_path


def _adv(pkg, ghsa, vulnerable, installed, dependents, severity="high"):
    return {"pkg": pkg, "ghsa": ghsa, "severity": severity, "vulnerable": vulnerable,
            "installed": installed, "dependents": dependents, "issue": ""}


def test_a_direct_dependency_is_left_to_dependabot(tmp_path, monkeypatch):
    root = _pkg(tmp_path, dependencies={"qs": "^6.15.0"})
    monkeypatch.setattr(p, "published", lambda _: ["6.15.3", "6.16.0"])
    proposals, blocked = p.plan(
        [_adv("qs", "GHSA-1", "<6.16.0", ["6.15.3"], ["@strapi/admin@npm:5.52.2"])],
        root, p.lock_versions(root / "yarn.lock"))
    assert proposals == []
    assert "direct dependency" in blocked[0]["why"]


def test_a_cross_line_fix_is_named_not_attempted(tmp_path, monkeypatch):
    root = _pkg(tmp_path)
    # stream-json 1.9.1, fix in 3.5.0: nothing inside the 1.x line helps.
    monkeypatch.setattr(p, "published", lambda _: ["1.9.1", "3.5.0"])
    proposals, blocked = p.plan(
        [_adv("stream-json", "GHSA-2", "<=3.4.0", ["1.9.1"], ["@strapi/x@npm:5.0.0"])],
        root, p.lock_versions(root / "yarn.lock"))
    assert proposals == []
    assert "no fix inside the 1.x line" in blocked[0]["why"]


def test_several_advisories_on_one_line_collapse_to_one_resolution(tmp_path, monkeypatch):
    root = _pkg(tmp_path)
    monkeypatch.setattr(p, "published", lambda _: ["7.28.0", "7.29.0", "7.29.1"])
    advisories = [
        _adv("undici", "GHSA-A", ">=7.0.0 <7.29.0", ["7.28.0"], ["cheerio@npm:1.2.0"]),
        _adv("undici", "GHSA-B", ">=7.0.0 <7.29.0", ["7.28.0"], ["cheerio@npm:1.2.0"],
             severity="critical"),
    ]
    proposals, _ = p.plan(advisories, root, p.lock_versions(root / "yarn.lock"))
    assert len(proposals) == 1
    assert proposals[0]["key"] == "cheerio/undici"
    # Newest in the line, not either advisory's first patched version.
    assert proposals[0]["target"] == "7.29.1"
    assert proposals[0]["ghsas"] == {"GHSA-A", "GHSA-B"}
    assert proposals[0]["severity"] == "critical"


def test_a_target_still_inside_the_vulnerable_range_is_refused(tmp_path, monkeypatch):
    root = _pkg(tmp_path)
    # Newest in the 6.x line is 6.15.3, which is itself vulnerable — proposing it would be
    # a pin that fixes nothing.
    monkeypatch.setattr(p, "published", lambda _: ["6.15.2", "6.15.3", "7.0.0"])
    proposals, blocked = p.plan(
        [_adv("qs", "GHSA-3", "<6.16.0", ["6.15.3"], ["@strapi/admin@npm:5.52.2"])],
        root, p.lock_versions(root / "yarn.lock"))
    assert proposals == []
    assert blocked


def test_an_advisory_whose_installed_versions_are_all_safe_is_ignored(tmp_path,
                                                                     monkeypatch):
    root = _pkg(tmp_path)
    monkeypatch.setattr(p, "published", lambda _: ["6.28.0", "6.29.0"])
    proposals, blocked = p.plan(
        [_adv("undici", "GHSA-4", ">=7.0.0 <7.29.0", ["6.28.0"], ["x@npm:1.0.0"])],
        root, p.lock_versions(root / "yarn.lock"))
    assert proposals == []
    assert blocked == []


# ------------------------------------------------------------------ writing

def test_resolutions_round_trip(tmp_path):
    root = _pkg(tmp_path, resolutions={"lodash": "^4.18.0"})
    before = p.apply_resolutions(root, {"tar": "^7.5.22"})
    assert before == {"lodash": "^4.18.0"}
    got = json.loads((root / "package.json").read_text())["resolutions"]
    assert got == {"lodash": "^4.18.0", "tar": "^7.5.22"}
    p.restore_resolutions(root, before)
    got = json.loads((root / "package.json").read_text())["resolutions"]
    assert got == {"lodash": "^4.18.0"}


def test_restore_removes_the_key_entirely_when_there_was_none(tmp_path):
    root = _pkg(tmp_path)
    p.apply_resolutions(root, {"tar": "^7.5.22"})
    p.restore_resolutions(root, {})
    assert "resolutions" not in json.loads((root / "package.json").read_text())


def test_apply_overwrites_an_existing_entry_rather_than_duplicating(tmp_path):
    root = _pkg(tmp_path, resolutions={"tar": "^7.5.19"})
    p.apply_resolutions(root, {"tar": "^7.5.22"})
    got = json.loads((root / "package.json").read_text())["resolutions"]
    assert got == {"tar": "^7.5.22"}


# ------------------------------------------------------------------ audit

def test_audit_drops_deprecation_notices(monkeypatch, tmp_path):
    lines = [
        # A deprecation notice: string ID, no GHSA URL. Must never become a pin.
        json.dumps({"value": "@koa/router", "children": {
            "ID": "@koa/router (deprecation)", "Severity": "moderate",
            "Issue": "Please upgrade", "Vulnerable Versions": "12.0.2",
            "Tree Versions": ["12.0.2"], "Dependents": ["@strapi/core@npm:5.52.2"]}}),
        json.dumps({"value": "tar", "children": {
            "ID": 1130588, "Severity": "high", "Issue": "node-tar: recursion",
            "URL": "https://github.com/advisories/GHSA-r292-9mhp-454m",
            "Vulnerable Versions": "<=7.5.20", "Tree Versions": ["7.5.19"],
            "Dependents": ["node-gyp@npm:12.1.0"]}}),
        "",
        "not json at all",
    ]

    class Proc:
        stdout = "\n".join(lines)
        stderr = ""
        returncode = 1  # yarn exits non-zero whenever it finds anything

    monkeypatch.setattr(p, "run", lambda *a, **k: Proc())
    got = p.audit(tmp_path)
    assert len(got) == 1
    assert got[0]["pkg"] == "tar"
    assert got[0]["ghsa"] == "GHSA-R292-9MHP-454M"
    assert got[0]["installed"] == ["7.5.19"]


# ------------------------------------------------------------------ reporting

def test_blocked_report_states_each_reason_once(tmp_path):
    blocked = [
        {"pkg": "brace-expansion", "installed_one": "1.1.16", "severity": "high",
         "why": "minimatch is itself in the tree at 2 versions"},
        {"pkg": "brace-expansion", "installed_one": "1.1.16", "severity": "high",
         "why": "minimatch is itself in the tree at 2 versions"},
        {"pkg": "vite", "installed_one": "5.4.21", "severity": "high",
         "why": "no fix inside the 5.x line"},
    ]
    out = p.render_blocked(blocked)
    assert out.count("brace-expansion") == 1
    assert out.count("vite") == 1


def test_summary_reads_as_a_sentence():
    applied = [{"key": "tar", "target": "7.5.22", "severity": "high", "ghsas": {"G1"}},
               {"key": "cheerio/undici", "target": "7.29.1", "severity": "high",
                "ghsas": {"G2", "G3"}}]
    got = p.summarise(applied, [], [{"pkg": "vite"}])
    assert "tar -> ^7.5.22 (high, 1 advisory)" in got
    assert "cheerio/undici -> ^7.29.1 (high, 2 advisories)" in got
    assert "1 need a human" in got
    assert p.summarise([], [], []) == "nothing to change"


# ------------------------------------------------------------------ the bump pass

LOCK_AFTER = LOCK.replace("version: 1.1.16", "version: 1.1.18").replace(
    "version: 5.0.7", "version: 5.0.9").replace("version: 6.15.3", "version: 6.16.0")


class _Yarn:
    """Fake `run`: a `yarn up` rewrites the lockfile to LOCK_AFTER (or to `lock_after`
    if given) and records every command; anything else exits 0 with no output."""

    def __init__(self, root, rc=0, rewrite_manifest=False, lock_after=LOCK_AFTER):
        self.root, self.rc, self.rewrite_manifest = root, rc, rewrite_manifest
        self.lock_after, self.calls = lock_after, []

    def __call__(self, cmd, cwd, check=False):
        self.calls.append(cmd)

        class Proc:
            returncode = self.rc
            stdout = ""
            stderr = "boom" if self.rc else ""
        if cmd[:2] == ["yarn", "up"] and self.rc == 0:
            (self.root / "yarn.lock").write_text(self.lock_after)
            if self.rewrite_manifest:
                (self.root / "package.json").write_text('{"name": "changed"}')
        return Proc()


def _audits(monkeypatch, *results):
    """`audit` returns each result in turn, then the last one forever."""
    queue = list(results)

    def fake(root):
        return queue.pop(0) if len(queue) > 1 else queue[0]
    monkeypatch.setattr(p, "audit", fake)


def test_bump_keeps_what_cleared_and_touches_only_the_lockfile(tmp_path, monkeypatch):
    root = _pkg(tmp_path, dependencies={"qs": "^6.11.0"})
    manifest = (root / "package.json").read_text()
    yarn = _Yarn(root)
    monkeypatch.setattr(p, "run", yarn)
    before = [_adv("brace-expansion", "GHSA-A", "<1.1.17", ["1.1.16"], ["minimatch@npm:3.1.5"]),
              _adv("brace-expansion", "GHSA-B", ">=4.0.0 <5.0.8", ["5.0.7"], ["x@npm:1"]),
              _adv("qs", "GHSA-C", "<6.16.0", ["6.15.3"], ["y@npm:1"], severity="low")]
    _audits(monkeypatch, [])                      # everything cleared
    bumped, left, note = p.bump_in_range(root, before)
    assert note == "" and left == []
    assert [b["pkg"] for b in bumped] == ["brace-expansion", "qs"]
    be = bumped[0]
    assert be["from"] == ["1.1.16", "5.0.7"] and be["to"] == ["1.1.18", "5.0.9"], be
    assert be["ghsas"] == {"GHSA-A", "GHSA-B"} and be["severity"] == "high"
    # A DIRECT dependency is bumped too: -R keeps the manifest range and moves the lock.
    assert bumped[1]["pkg"] == "qs"
    assert (root / "package.json").read_text() == manifest
    assert len(yarn.calls) == 1
    assert yarn.calls[0][:3] == ["yarn", "up", "-R"] and "--mode=update-lockfile" in yarn.calls[0]


def test_a_package_that_moved_without_clearing_is_put_back(tmp_path, monkeypatch):
    root = _pkg(tmp_path)
    yarn = _Yarn(root)
    monkeypatch.setattr(p, "run", yarn)
    before = [_adv("brace-expansion", "GHSA-A", "<1.1.17", ["1.1.16"], ["m@npm:3"]),
              _adv("qs", "GHSA-C", "<6.17.0", ["6.15.3"], ["y@npm:1"])]
    still_qs = [_adv("qs", "GHSA-C", "<6.17.0", ["6.16.0"], ["y@npm:1"])]
    _audits(monkeypatch, still_qs, still_qs)      # qs moved to 6.16.0, still vulnerable
    bumped, left, note = p.bump_in_range(root, before)
    assert [b["pkg"] for b in bumped] == ["brace-expansion"]
    assert left == still_qs
    # Two runs: the discovery run with both names, then the keep run with only the helpful.
    assert len(yarn.calls) == 2
    assert "qs" in yarn.calls[0] and "qs" not in yarn.calls[1]
    assert "brace-expansion" in yarn.calls[1]


def test_nothing_cleared_means_nothing_kept(tmp_path, monkeypatch):
    root = _pkg(tmp_path)
    monkeypatch.setattr(p, "run", _Yarn(root))
    before = [_adv("qs", "GHSA-C", "<6.17.0", ["6.15.3"], ["y@npm:1"])]
    _audits(monkeypatch, before)
    bumped, left, note = p.bump_in_range(root, before)
    assert bumped == [] and left == before and note == ""
    assert (root / "yarn.lock").read_text() == LOCK            # restored byte for byte


def test_a_rewritten_manifest_abandons_the_pass(tmp_path, monkeypatch):
    root = _pkg(tmp_path, dependencies={"qs": "^6.11.0"})
    manifest = (root / "package.json").read_text()
    monkeypatch.setattr(p, "run", _Yarn(root, rewrite_manifest=True))
    before = [_adv("qs", "GHSA-C", "<6.16.0", ["6.15.3"], ["y@npm:1"])]
    _audits(monkeypatch, [])
    bumped, left, note = p.bump_in_range(root, before)
    assert bumped == [] and left == before
    assert "package.json" in note
    assert (root / "package.json").read_text() == manifest
    assert (root / "yarn.lock").read_text() == LOCK


def test_a_failed_yarn_up_restores_and_says_why(tmp_path, monkeypatch):
    root = _pkg(tmp_path)
    monkeypatch.setattr(p, "run", _Yarn(root, rc=1))
    before = [_adv("qs", "GHSA-C", "<6.16.0", ["6.15.3"], ["y@npm:1"])]
    _audits(monkeypatch, before)
    bumped, left, note = p.bump_in_range(root, before)
    assert bumped == [] and left == before
    assert "failed" in note and "boom" in note
    assert (root / "yarn.lock").read_text() == LOCK


def test_no_advisories_means_no_yarn_run_at_all(tmp_path, monkeypatch):
    root = _pkg(tmp_path)
    yarn = _Yarn(root)
    monkeypatch.setattr(p, "run", yarn)
    assert p.bump_in_range(root, []) == ([], [], "")
    assert yarn.calls == []


def test_bumped_report_names_versions_and_advisories():
    out = p.render_bumped([{"pkg": "axios", "from": ["1.9.0"], "to": ["1.20.0"],
                            "severity": "high", "ghsas": {"GHSA-B", "GHSA-A"}}])
    assert out == "- `axios` 1.9.0 → 1.20.0 (high, GHSA-A, GHSA-B)"


def test_summary_counts_the_bump_pass_first():
    bumped = [{"pkg": "axios", "ghsas": {"A", "B"}}, {"pkg": "qs", "ghsas": {"C"}}]
    got = p.summarise([], [], [], bumped)
    assert got.startswith("2 packages re-resolved in range (3 advisories)"), got
    applied = [{"key": "tar", "target": "7.5.22", "severity": "high", "ghsas": {"G1"}}]
    got = p.summarise(applied, [], [{"pkg": "vite"}], bumped)
    assert "re-resolved" in got and "tar -> ^7.5.22" in got and "1 need a human" in got
